name: CI Pipeline - Testing Branch

on:
  push:
    branches:
      - testing

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      # Customer Service
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Test Customer Service
        run: |
          cd backend/customer_service
          pip install -r requirements.txt
          pytest tests/ -v --cov=. --cov-report=term-missing
      
      - name: Test Order Service
        run: |
          cd backend/order_service
          pip install -r requirements.txt
          pytest tests/ -v --cov=. --cov-report=term-missing
      
      - name: Test Product Service
        run: |
          cd backend/product_service
          pip install -r requirements.txt
          pytest tests/ -v --cov=. --cov-report=term-missing
      
      # Build and Push Images (only if tests pass)
      - name: Login to Azure Container Registry
        run: |
          echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ secrets.ACR_LOGIN_SERVER }} \
            -u ${{ secrets.ACR_USERNAME }} --password-stdin
      
      - name: Build and Push Customer Service
        run: |
          cd backend/customer_service
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/customer-service:${{ github.sha }} .
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/customer-service:latest .
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/customer-service:${{ github.sha }}
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/customer-service:latest
      
      - name: Build and Push Order Service
        run: |
          cd backend/order_service
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/order-service:${{ github.sha }} .
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/order-service:latest .
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/order-service:${{ github.sha }}
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/order-service:latest
      
      - name: Build and Push Product Service
        run: |
          cd backend/product_service
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/product-service:${{ github.sha }} .
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/product-service:latest .
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/product-service:${{ github.sha }}
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/product-service:latest
      
      - name: Build and Push Frontend
        run: |
          cd frontend
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/frontend:${{ github.sha }} .
          docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/frontend:latest .
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/frontend:${{ github.sha }}
          docker push ${{ secrets.ACR_LOGIN_SERVER }}/frontend:latest
      
      - name: Trigger Staging Deployment
        if: success()
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: staging-deploy
          client-payload: '{"sha": "${{ github.sha }}"}'