name: Deploy to Production

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

env:
  PROD_RG: sit722-rg
  PROD_AKS: sit722-aks-prod

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event.pull_request.merged == true
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Get Production AKS Credentials
        run: |
          az aks get-credentials \
            --resource-group ${{ env.PROD_RG }} \
            --name ${{ env.PROD_AKS }} \
            --overwrite-existing
      
      - name: Deploy to Production
        run: |
          for file in k8s/*.yaml; do
            sed -i "s|IMAGE_TAG|latest|g" "$file"
          done
          kubectl apply -f k8s/
      
      - name: Wait for Deployments
        run: |
          kubectl rollout status deployment/customer-service --timeout=600s || true
          kubectl rollout status deployment/order-service --timeout=600s || true
          kubectl rollout status deployment/product-service --timeout=600s || true
          kubectl rollout status deployment/frontend --timeout=600s || true
      
      - name: Check Status
        run: |
          kubectl get deployments
          kubectl get pods
          kubectl get services
